package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"log"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/tools/go/packages"
)

func main() {
	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedSyntax | packages.NeedTypes | packages.NeedTypesInfo | packages.NeedImports,
		Dir:  ".",
	}

	pkgs, err := packages.Load(cfg, "./...")
	if err != nil {
		log.Fatalf("Ошибка загрузки пакетов: %v", err)
	}

	resetableNamedTypes := make(map[*types.Named]bool)
	structsToGenerate := make(map[*packages.Package][]*ast.TypeSpec)

	for _, pkg := range pkgs {
		if pkg.Types == nil {
			continue
		}
		for _, file := range pkg.Syntax {
			for _, decl := range file.Decls {
				genDecl, ok := decl.(*ast.GenDecl)
				if !ok || genDecl.Tok != token.TYPE {
					continue
				}
				for _, spec := range genDecl.Specs {
					typeSpec, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}
					_, isStruct := typeSpec.Type.(*ast.StructType)
					if !isStruct {
						continue
					}
					if hasGenerateResetComment(genDecl, typeSpec) {
						obj := pkg.TypesInfo.Defs[typeSpec.Name]
						if obj != nil {
							if named, ok := obj.Type().(*types.Named); ok {
								resetableNamedTypes[named] = true
							}
						}
						structsToGenerate[pkg] = append(structsToGenerate[pkg], typeSpec)
					}
				}
			}
		}
	}

	// Второй проход: генерация методов Reset() и запись в файлы
	for pkg, specs := range structsToGenerate {
		var buf bytes.Buffer
		buf.WriteString("// Code generated by reset generator. DO NOT EDIT.\n\n")
		buf.WriteString(fmt.Sprintf("package %s\n\n", pkg.Name))

		for _, spec := range specs {
			structType := spec.Type.(*ast.StructType)
			receiverName := generateReceiverName(spec.Name.Name, structType.Fields.List)

			buf.WriteString(fmt.Sprintf("func (%s *%s) Reset() {\n", receiverName, spec.Name.Name))
			buf.WriteString(fmt.Sprintf("    if %s == nil {\n        return\n    }\n\n", receiverName))

			for _, field := range structType.Fields.List {
				if len(field.Names) == 0 {
					continue
				}
				for _, fName := range field.Names {
					fObj := pkg.TypesInfo.Defs[fName]
					if fObj == nil {
						continue
					}

					expr := fmt.Sprintf("%s.%s", receiverName, fName.Name)
					stmts := genResetForType(expr, fObj.Type(), resetableNamedTypes)
					for _, s := range stmts {
						buf.WriteString("    " + s + "\n")
					}
				}
			}
			buf.WriteString("}\n\n")
		}

		// Форматируем сгенерированный код с помощью gofmt
		src, err := format.Source(buf.Bytes())
		if err != nil {
			log.Printf("Не удалось отформатировать код для пакета %s: %v\n", pkg.Name, err)
			src = buf.Bytes()
		}

		if len(pkg.GoFiles) == 0 {
			continue
		}

		// Определяем директорию пакета и сохраняем файл reset.gen.go
		dir := filepath.Dir(pkg.GoFiles[0])
		outPath := filepath.Join(dir, "reset.gen.go")

		err = os.WriteFile(outPath, src, 0644)
		if err != nil {
			log.Printf("Ошибка записи файла %s: %v\n", outPath, err)
		} else {
			log.Printf("Сгенерирован файл: %s\n", outPath)
		}
	}
}

// hasGenerateResetComment проверяет наличие директивы // generate:reset в комментариях
func hasGenerateResetComment(genDecl *ast.GenDecl, typeSpec *ast.TypeSpec) bool {
	check := func(cg *ast.CommentGroup) bool {
		if cg == nil {
			return false
		}
		for _, c := range cg.List {
			if strings.Contains(c.Text, "generate:reset") {
				return true
			}
		}
		return false
	}
	return check(genDecl.Doc) || check(typeSpec.Doc) || check(typeSpec.Comment)
}

// hasResetMethod проверяет, имеет ли тип метод Reset()
func hasResetMethod(t types.Type, resetable map[*types.Named]bool) bool {
	if named, ok := t.(*types.Named); ok {
		if resetable[named] {
			return true
		}
	}
	if ptr, ok := t.(*types.Pointer); ok {
		if named, ok := ptr.Elem().(*types.Named); ok {
			if resetable[named] {
				return true
			}
		}
	}

	check := func(typ types.Type) bool {
		if typ == nil {
			return false
		}
		mset := types.NewMethodSet(typ)
		for i := 0; i < mset.Len(); i++ {
			m := mset.At(i)
			if m.Obj().Name() == "Reset" {
				sig, ok := m.Type().(*types.Signature)
				if ok && sig.Params().Len() == 0 && sig.Results().Len() == 0 {
					return true
				}
			}
		}
		return false
	}

	if check(t) {
		return true
	}
	if _, isPtr := t.(*types.Pointer); !isPtr {
		if check(types.NewPointer(t)) {
			return true
		}
	}
	return false
}

// genResetForType рекурсивно генерирует инструкции для сброса поля
func genResetForType(expr string, t types.Type, resetable map[*types.Named]bool) []string {
	var stmts []string
	underlying := t.Underlying()

	switch u := underlying.(type) {
	case *types.Basic:
		info := u.Info()
		if info&types.IsBoolean != 0 {
			stmts = append(stmts, fmt.Sprintf("%s = false", expr))
		} else if info&types.IsInteger != 0 {
			stmts = append(stmts, fmt.Sprintf("%s = 0", expr))
		} else if info&types.IsFloat != 0 {
			stmts = append(stmts, fmt.Sprintf("%s = 0.0", expr))
		} else if info&types.IsComplex != 0 {
			stmts = append(stmts, fmt.Sprintf("%s = 0", expr))
		} else if info&types.IsString != 0 {
			stmts = append(stmts, fmt.Sprintf("%s = \"\"", expr))
		} else {
			stmts = append(stmts, fmt.Sprintf("var zero %s", t.String()))
			stmts = append(stmts, fmt.Sprintf("%s = zero", expr))
		}
	case *types.Slice:
		stmts = append(stmts, fmt.Sprintf("%s = %s[:0]", expr, expr))
	case *types.Map:
		stmts = append(stmts, fmt.Sprintf("clear(%s)", expr))
	case *types.Pointer:
		elem := u.Elem()
		stmts = append(stmts, fmt.Sprintf("if %s != nil {", expr))
		if hasResetMethod(elem, resetable) {
			stmts = append(stmts, fmt.Sprintf("    %s.Reset()", expr))
		} else if _, isIface := elem.Underlying().(*types.Interface); isIface {
			stmts = append(stmts, fmt.Sprintf("    if resetter, ok := (%s).(interface{ Reset() }); ok {", expr))
			stmts = append(stmts, "        resetter.Reset()")
			stmts = append(stmts, "    }")
		} else {
			inner := genResetForType("*"+expr, elem, resetable)
			for _, s := range inner {
				stmts = append(stmts, "    "+s)
			}
		}
		stmts = append(stmts, "}")
	case *types.Struct:
		if hasResetMethod(t, resetable) {
			stmts = append(stmts, fmt.Sprintf("%s.Reset()", expr))
		}
	case *types.Interface:
		stmts = append(stmts, fmt.Sprintf("if %s != nil {", expr))
		stmts = append(stmts, fmt.Sprintf("    if resetter, ok := %s.(interface{ Reset() }); ok {", expr))
		stmts = append(stmts, "        resetter.Reset()")
		stmts = append(stmts, "    }")
		stmts = append(stmts, "}")
	case *types.Array:
		stmts = append(stmts, fmt.Sprintf("var zero %s", t.String()))
		stmts = append(stmts, fmt.Sprintf("%s = zero", expr))
	case *types.Chan, *types.Signature:
		stmts = append(stmts, fmt.Sprintf("%s = nil", expr))
	}
	return stmts
}

// generateReceiverName генерирует имя receiver'а для метода Reset.
func generateReceiverName(typeName string, fields []*ast.Field) string {
	lowerName := toLowerCamel(typeName)

	var candidates []string
	if len(lowerName) <= 15 {
		candidates = append(candidates, lowerName)
	}

	// Добавляем короткие варианты как fallback (первые 3 буквы оригинального имени)
	origLower := strings.ToLower(typeName)
	for i := 1; i <= min(3, len(origLower)); i++ {
		candidates = append(candidates, origLower[:i])
	}

	// Собираем имена всех полей для проверки конфликтов
	fieldNames := extractFieldNames(fields)

	// Ищем первого кандидата, который не конфликтует с полями
	for _, c := range candidates {
		if !fieldNames[c] {
			return c
		}
	}

	fallbacks := []string{"x", "y", "z", "rcv", "val", "obj", "receiver"}
	for _, f := range fallbacks {
		if !fieldNames[f] {
			return f
		}
	}

	return "receiver"
}

// toLowerCamel преобразует имя типа в lowerCamelCase.
func toLowerCamel(s string) string {
	if s == "" {
		return ""
	}
	return strings.ToLower(s[:1]) + s[1:]
}

// extractFieldNames собирает все имена полей структуры
func extractFieldNames(fields []*ast.Field) map[string]bool {
	names := make(map[string]bool)
	for _, f := range fields {
		if len(f.Names) > 0 {
			for _, fName := range f.Names {
				names[fName.Name] = true
			}
		} else {
			switch t := f.Type.(type) {
			case *ast.Ident:
				names[t.Name] = true
			case *ast.StarExpr:
				if ident, ok := t.X.(*ast.Ident); ok {
					names[ident.Name] = true
				}
			case *ast.SelectorExpr:
				names[t.Sel.Name] = true
			}
		}
	}
	return names
}
